from __future__ import annotations

import json
import re

from .base import CompiledArtifact, TargetCompiler
from ..uam import NodeKind, UAMProcess


def safe_identifier(value: str) -> str:
    result = re.sub(r"\W+", "_", value).strip("_").lower()
    return result or "flowrebase_process"


class PythonTargetCompiler(TargetCompiler):
    target = "python"

    def compile(self, process: UAMProcess) -> CompiledArtifact:
        name = safe_identifier(process.name)
        lines = [
            '"""Generated by FlowRebase. Review and run ProofRun before production use."""',
            "from __future__ import annotations",
            "",
            "from typing import Any",
            "",
            f"async def {name}(input_data: dict[str, Any], adapters: dict[str, Any]) -> dict[str, Any]:",
            "    output: dict[str, Any] = {}",
            "    vars: dict[str, Any] = {}",
        ]
        warnings: list[str] = []
        for node in process.nodes:
            if node.kind in {NodeKind.START, NodeKind.END}:
                continue
            lines.append(f"    # {node.kind.value}: {node.name}")
            if node.kind == NodeKind.API_CALL:
                lines.append(f"    await adapters['api'].execute({json.dumps(node.config)})")
            elif node.kind == NodeKind.DATABASE:
                lines.append(f"    await adapters['database'].execute({json.dumps(node.config)})")
            elif node.kind == NodeKind.NOTIFICATION:
                lines.append(f"    await adapters['notification'].execute({json.dumps(node.config)})")
            elif node.kind in {NodeKind.UI_ACTION, NodeKind.ROBOT_ACTION}:
                lines.append(f"    await adapters['robot'].execute({json.dumps(node.config)})")
                warnings.append(f"Robot activity '{node.name}' requires a target-specific robot adapter.")
            elif node.kind in {NodeKind.HUMAN, NodeKind.APPROVAL}:
                lines.append(f"    await adapters['human'].request({json.dumps(node.config)})")
            elif node.kind == NodeKind.AGENT:
                lines.append(f"    await adapters['agent'].execute({json.dumps(node.config)})")
            elif node.kind == NodeKind.POLICY:
                lines.append(f"    await adapters['policy'].check({json.dumps(node.config)})")
            elif node.kind == NodeKind.DECISION:
                expression = node.config.get("expression")
                if expression:
                    lines.append(f"    # Decision expression from source: {expression!r}")
                lines.append("    pass")
            else:
                set_output = node.config.get("set_output", {})
                if set_output:
                    for key, value in set_output.items():
                        if isinstance(value, str) and value.startswith("="):
                            warnings.append(f"Expression for output '{key}' requires manual target validation: {value}")
                            lines.append(f"    # output[{key!r}] = {value[1:]}")
                        else:
                            lines.append(f"    output[{key!r}] = {value!r}")
                else:
                    lines.append("    pass")
        lines.extend(["    return output", ""])
        return CompiledArtifact(
            target=self.target,
            filename=f"{name}.py",
            media_type="text/x-python",
            content="\n".join(lines),
            warnings=sorted(set(warnings)),
        )
